name: pool_buddy
description: A companion app for pool buddy.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_charts: ^0.1.10
  flutter_swiper : ^1.1.4
  percent_indicator: ^1.0.9
  flushbar: ^0.9.2
  charts_flutter: ^0.4.0
  mqtt_client: ^3.3.4
  fluro: ^1.3.5
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: ^0.6.2+1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   
  - assets/login.jpg
  - assets/home.jpeg
  - assets/tick.png
  - assets/avatars/avatar-1.jpg
  - assets/avatars/avatar-2.jpg
  - assets/avatars/avatar-3.jpg
  - assets/avatars/avatar-4.jpg
  - assets/avatars/avatar-5.jpg
  - assets/avatars/avatar-6.jpg
  - assets/avatars/default-avatar.jpg
  - assets/images/bg.gif
  - assets/images/AMSPL.png
  - assets/images/home_bg.gif
  - assets/images/home_bg.jpg
  - assets/images/home_bg_2.jpeg
  - assets/images/home_bg_3.jpg
  - assets/images/logo.png
  - assets/images/login.png
  - assets/images/mars.png
  - assets/images/neptune.png
  - assets/images/moon.png
  - assets/images/earth.png
  - assets/images/mercury.png

  fonts:
       - family: petita
         fonts:
           - asset: assets/fonts/PetitaMedium.ttf
           - asset: assets/fonts/PetitaBold.ttf
             weight: 700
           - asset: assets/fonts/PetitaLight.ttf
             weight: 300
       - family: gidole
         fonts:
           - asset: assets/fonts/Gidole-Regular.ttf
